'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function AuthForm({mode='login'}:{mode?:'login'|'activate'|'setup'}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 useEffect(()=>{if(mode!=='login'){setToken(window.location.hash.slice(1));history.replaceState(null,'',location.pathname);}},[mode]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode!=='login'&&password!==confirm){setError('As senhas não coincidem.');return;}setBusy(true);try{const r=await fetch('/api/auth/'+(mode==='login'?'login':'activate'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,...(mode==='login'?{}:{token,setup:mode==='setup'})})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error||'Não foi possível entrar.');setPassword('');setConfirm('');if(mode==='login')window.location.assign('/administrador');else setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="auth-shell"><a href="/" className="admin-brand">TENDA <span>DA ADORAÇÃO</span></a><section className="editor auth-card"><span className="eyebrow">ACESSO RESTRITO</span><h1>{mode==='login'?'Administração':mode==='setup'?'Configure seu acesso':'Ative sua conta'}</h1><p>{mode==='login'?'Entre com o e-mail e a senha da sua conta autorizada.':'Escolha uma senha exclusiva com pelo menos 12 caracteres.'}</p>{done?<div role="status"><p>Senha cadastrada. Agora você pode entrar.</p><a className="action" href="/administrador/login">Ir para o login</a></div>:<form onSubmit={submit}><fieldset disabled={busy}><label htmlFor="auth-email">E-mail</label><Input id="auth-email" type="email" autoComplete="username" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="auth-password">{mode==='login'?'Senha':'Nova senha'}</label><Input id="auth-password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/>{mode!=='login'&&<><label htmlFor="auth-confirm">Repita a senha</label><Input id="auth-confirm" type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/>{!token&&<p role="alert">Abra o link de ativação fornecido pelo administrador.</p>}</>}<Button type="submit" disabled={busy||(mode!=='login'&&!token)}>{busy?'Aguarde…':mode==='login'?'Entrar':'Cadastrar senha'}</Button></fieldset></form>}{error&&<p role="alert" className="notice error">{error}</p>}{mode==='login'&&<p className="editor-hint">Não há cadastro público. Para solicitar acesso ou recuperar a conta de editora, fale com o administrador.</p>}</section><a href="/">Voltar ao site</a></main>;
}
