'use client';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
type User={id:string;email:string;name:string;role:string;enabled:number;activated:number};
export default function UsersEditor(){const [users,setUsers]=useState<User[]>([]),[email,setEmail]=useState(''),[name,setName]=useState(''),[link,setLink]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<{user:User;action:string}|null>(null);
async function load(){const r=await fetch('/api/admin/users');if(!r.ok)throw Error('Não foi possível carregar as contas.');setUsers(await r.json());}
useEffect(()=>{load().catch(e=>setError(e.message));},[]);
async function send(method:string,data:unknown){setBusy(true);setError('');setMessage('');setLink('');try{const r=await fetch('/api/admin/users',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await r.json() as {error?:string;link?:string};if(!r.ok)throw Error(body.error||'Não foi possível salvar.');setLink(body.link||'');setMessage(body.link?'Convite pronto. Envie o link somente para a pessoa autorizada.':'Permissão atualizada.');setPending(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <section className="editor"><h2>Pessoas autorizadas</h2><p>Editoras podem publicar fotos e eventos. Só você controla contas e informações da igreja.</p><form onSubmit={e=>{e.preventDefault();void send('POST',{email,name});}}><fieldset disabled={busy}><label htmlFor="invite-name">Nome da pessoa</label><Input id="invite-name" required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="invite-email">E-mail autorizado</label><Input id="invite-email" type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/><Button type="submit">Criar convite de editora</Button></fieldset></form>{message&&<p role="status">{message}</p>}{link&&<div className="notice"><label htmlFor="invite-link">Link privado · válido por 48 horas e para um único uso</label><Input id="invite-link" readOnly value={link} onFocus={e=>e.target.select()}/><p>O link não é enviado por e-mail automaticamente. A pessoa deverá informar o e-mail autorizado e escolher a própria senha.</p></div>}{error&&<p role="alert" className="notice error">{error}</p>}<div className="account-list">{users.map(user=><article key={user.id}><strong>{user.name}</strong><p>{user.email}</p><p>{user.role==='owner'?'Administrador':!user.enabled?'Bloqueada':user.activated?'Editora ativa':'Ativação pendente'}</p>{user.role==='editor'&&<div className="editor-actions"><Button variant="outline" disabled={busy} onClick={()=>setPending({user,action:user.enabled?'disable':'enable'})}>{user.enabled?'Bloquear acesso':'Liberar acesso'}</Button><Button variant="outline" disabled={busy} onClick={()=>setPending({user,action:'invite'})}>Renovar convite / senha</Button></div>}</article>)}</div><AlertDialog open={!!pending} onOpenChange={open=>{if(!open&&!busy)setPending(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Atualizar acesso de {pending?.user.name}?</AlertDialogTitle><AlertDialogDescription>{pending?.action==='invite'?'A senha atual deixará de funcionar e as sessões serão encerradas. Um novo link permitirá definir outra senha.':pending?.action==='disable'?'A pessoa perderá imediatamente o acesso ao painel.':'A pessoa poderá entrar com a senha já cadastrada. Se ainda não ativou a conta, renove o convite.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();if(pending)void send('PATCH',{id:pending.user.id,action:pending.action});}}>Confirmar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
