import Community from './community';
export default function Home(){return <>
  <a className="skip" href="#conteudo">Pular para o conteúdo</a>
  <header className="header">
    <a className="brand" href="#inicio" aria-label="Tenda da Adoração — início"><span className="brand-logo"><img src="logo.jpeg" alt="" width="500" height="500"/></span><span>TENDA<span className="brand-sub">DA ADORAÇÃO</span></span></a>
    <nav aria-label="Navegação principal"><a href="#galeria">Galeria</a><a href="#eventos">Eventos</a><a href="#cultos">Nossos cultos</a><a className="nav-button" href="#boas-vindas">Como chegar <span aria-hidden="true">↗</span></a></nav>
  </header>
  <main id="conteudo">
    <section className="hero" id="inicio" aria-labelledby="hero-title">
      <div className="hero-top"><span>FÉ QUE ACOLHE. AMOR QUE TRANSFORMA.</span><span className="hero-reference">TENDA DA ADORAÇÃO</span></div>
      <div className="hero-grid"><div className="hero-copy"><h1 id="hero-title">Um lugar para<br/>pertencer.<br/><em>Uma família<br/>para caminhar.</em></h1><p>Há lugar para você aqui. Encontre acolhimento, fortaleça sua fé e caminhe com a gente na presença de Deus.</p><a className="button light" href="#cultos">Participe de um culto <span aria-hidden="true">↗</span></a></div>
      <div className="identity"><div className="identity-label"><span>NOSSA FÉ NOS REÚNE</span><span aria-hidden="true">✦</span></div><img className="hero-logo" src="logo.jpeg" alt="Logo da Tenda da Adoração: uma tenda sobre uma família, com detalhes em vermelho e verde" width="500" height="500"/><div className="identity-caption"><span>Uma igreja<br/><strong>reestruturando famílias.</strong></span><span className="caption-mark" aria-hidden="true">↗</span></div></div></div>
      <div className="hero-bottom"><span>De portas abertas. De coração também.</span><a href="#essencia">Descubra nossa essência <span aria-hidden="true">↓</span></a></div>
    </section>
    <section className="essence section" id="essencia" aria-labelledby="essence-title"><div className="section-label"><span className="line"></span> NOSSA ESSÊNCIA</div><div className="essence-grid"><h2 id="essence-title">A fé nos une.<br/>O amor nos faz<br/><em>família.</em></h2><div className="essence-copy"><p className="lead">Tenda da Adoração.<br/>Uma igreja reestruturando famílias.</p><p>Cremos no poder do amor de Deus para renovar histórias. Nosso convite é para uma caminhada de fé, feita de encontros, cuidado e comunhão.</p><p>Seja qual for o seu momento, você é bem-vindo para conhecer a Tenda e compartilhar essa caminhada.</p></div></div></section>
    <section className="family section" id="familia" aria-labelledby="family-title"><div className="section-label"><span className="line"></span> JUNTOS NA CAMINHADA</div><div className="family-heading"><h2 id="family-title">A vida com Deus<br/>se vive <em>em comunhão.</em></h2><p>Fé no coração.<br/>Cuidado em cada encontro.</p></div><div className="values"><article><span className="value-number">01 /</span><h3>Adoração</h3><p>Um coração voltado a Deus, com gratidão, oração e entrega.</p></article><article><span className="value-number">02 /</span><h3>Acolhimento</h3><p>Espaço para chegar como você é e encontrar companhia na caminhada.</p></article><article><span className="value-number">03 /</span><h3>Família</h3><p>Laços fortalecidos pelo amor, pelo cuidado e pela presença de Deus.</p></article></div></section>
    <section className="services section" id="cultos" aria-labelledby="services-title"><div className="section-label"><span className="line"></span> NOSSOS ENCONTROS</div><div className="family-heading"><h2 id="services-title">Uma pausa na rotina.<br/>Um encontro <em>com Deus.</em></h2><p>Esperamos por você<br/>em Porto Velho.</p></div><div className="service-list"><article><div className="service-day">QUARTA-FEIRA</div><h3>Quarta da Vitória</h3><span className="service-time">19h30</span></article><article><div className="service-day">DOMINGO</div><h3>Culto da Família</h3><span className="service-time">18h</span></article></div></section>
    <Community/><section className="welcome section" id="boas-vindas" aria-labelledby="welcome-title"><div className="section-label"><span className="line"></span> SEU LUGAR TAMBÉM É AQUI</div><h2 id="welcome-title">Uma nova história<br/>pode começar com<br/><em>um encontro.</em></h2><p>Você e sua família são bem-vindos<br/>à Tenda da Adoração.</p><address>Rua Cartuana, 548 · Bairro Tiradentes<br/>Porto Velho – RO</address><a className="button light" href="https://www.google.com/maps/search/?api=1&amp;query=Rua%20Cartuana%20548%20Tiradentes%20Porto%20Velho%20RO" target="_blank" rel="noopener noreferrer">Como chegar <span aria-hidden="true">↗</span></a><span className="welcome-word" aria-hidden="true">TENDA</span></section>
  </main>
  <footer><a className="footer-title" href="#inicio">TENDA DA ADORAÇÃO</a><p>Uma igreja reestruturando famílias.</p><a href="/painel">Área de publicação ↗</a></footer>
</>;}
