'use client';
import {useState,useEffect} from 'react';
import {defaults,type ChurchSettings} from '@/lib/church-settings';
import Community from './community';
import ScrollReveal from './scroll-reveal';
export default function Home(){const [settings,setSettings]=useState<ChurchSettings>(defaults),[settingsError,setSettingsError]=useState(false),[now,setNow]=useState(Date.now());useEffect(()=>{let active=true;const load=()=>fetch('/api/settings').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<ChurchSettings>}).then(data=>{if(active){setSettings(data);setSettingsError(false);}}).catch(()=>{if(active)setSettingsError(true);});void load();const timer=setInterval(()=>{setNow(Date.now());void load();},60000);return()=>{active=false;clearInterval(timer);};},[]);return <><ScrollReveal/>
  <a className="skip" href="#conteudo">Pular para o conteúdo</a>
  <header className="header">
    <a className="brand" href="#inicio" aria-label="Tenda da Adoração — início"><span className="brand-logo"><img src="logo.jpeg" alt="" width="500" height="500"/></span><span>TENDA<span className="brand-sub">DA ADORAÇÃO</span></span></a>
    <nav aria-label="Navegação principal"><a href="#galeria">Galeria</a><a href="#eventos">Eventos</a><a href="#cultos">Nossos cultos</a><a className="nav-button" href="#boas-vindas">Como chegar <span aria-hidden="true">↗</span></a></nav>
  </header>
  <main id="conteudo">{settingsError&&<p role="status" className="settings-unavailable">Não foi possível atualizar as informações da igreja. Tente recarregar a página.</p>}{settings.notice.enabled&&(!settings.notice.expiresAt||Date.parse(settings.notice.expiresAt)>now)&&<aside className="church-notice" aria-label="Aviso da igreja"><h2>{settings.notice.title}</h2><p>{settings.notice.message}</p></aside>}
    <section className="hero" id="inicio" aria-labelledby="hero-title">
      <div className="hero-top"><span>FÉ QUE ACOLHE. AMOR QUE TRANSFORMA.</span><span className="hero-reference">TENDA DA ADORAÇÃO</span></div>
      <div className="hero-grid"><div className="hero-copy"><span className="hero-eyebrow">NOSSA PALAVRA TEMA</span><h1 id="hero-title" className="theme-title">Vivendo com <em>propósito</em> para poder <em>prosperar!</em></h1><div className="theme-reference"><span aria-hidden="true"/>Jeremias 29:11</div><p>Há lugar para você aqui. Encontre acolhimento, fortaleça sua fé e caminhe com a gente na presença de Deus.</p><div className="hero-actions"><a className="button light" href="#cultos">Conheça nossos cultos</a><a className="button hero-secondary" href="#boas-vindas">Planeje sua visita</a></div></div>
      <div className="identity"><div className="identity-label">FÉ, ACOLHIMENTO E FAMÍLIA</div><div className="identity-art"><img className="hero-logo" src="logo.jpeg" alt="Logo da Tenda da Adoração" width="500" height="500"/></div><div className="identity-caption"><span>Uma igreja<br/><strong>reestruturando famílias.</strong></span></div><div className="identity-visit"><span>VENHA NOS CONHECER</span><p>{settings.address}</p></div></div></div>
      <div className="hero-bottom"><span>De portas abertas. De coração também.</span><a href="#essencia">Descubra nossa essência <span aria-hidden="true">↓</span></a></div>
    </section>
    <section className="essence section" id="essencia" aria-labelledby="essence-title"><div className="section-label"><span className="line"></span> NOSSA ESSÊNCIA</div><div className="essence-grid"><h2 id="essence-title">A fé nos une.<br/>O amor nos faz<br/><em>família.</em></h2><div className="essence-copy"><p className="lead">Tenda da Adoração.<br/>Uma igreja reestruturando famílias.</p><p>Cremos no poder do amor de Deus para renovar histórias. Nosso convite é para uma caminhada de fé, feita de encontros, cuidado e comunhão.</p><p>Seja qual for o seu momento, você é bem-vindo para conhecer a Tenda e compartilhar essa caminhada.</p></div></div></section>
    <section className="family section" id="familia" aria-labelledby="family-title"><div className="section-label"><span className="line"></span> JUNTOS NA CAMINHADA</div><div className="family-heading"><h2 id="family-title">A vida com Deus<br/>se vive <em>em comunhão.</em></h2><p>Fé no coração.<br/>Cuidado em cada encontro.</p></div><div className="values"><article><span className="value-number">01 /</span><h3>Adoração</h3><p>Um coração voltado a Deus, com gratidão, oração e entrega.</p></article><article><span className="value-number">02 /</span><h3>Acolhimento</h3><p>Espaço para chegar como você é e encontrar companhia na caminhada.</p></article><article><span className="value-number">03 /</span><h3>Família</h3><p>Laços fortalecidos pelo amor, pelo cuidado e pela presença de Deus.</p></article></div></section>
    <section className="services section" id="cultos" aria-labelledby="services-title"><div className="section-label"><span className="line"></span> NOSSOS ENCONTROS</div><div className="family-heading"><h2 id="services-title">Uma pausa na rotina.<br/>Um encontro <em>com Deus.</em></h2><p>Esperamos por você<br/>em Porto Velho.</p></div><div className="service-list">{settings.services.map((service,i)=><article key={i}><div className="service-day">{service.day}</div><h3>{service.name}</h3><span className="service-time">{service.time.replace(':','h')}</span></article>)}</div></section>
    <Community/><section className="welcome section" id="boas-vindas" aria-labelledby="welcome-title"><div className="section-label"><span className="line"></span> SEU LUGAR TAMBÉM É AQUI</div><h2 id="welcome-title">Uma nova história<br/>pode começar com<br/><em>um encontro.</em></h2><p>Você e sua família são bem-vindos<br/>à Tenda da Adoração.</p><address>{settings.address}</address><a className="button light" href={settings.mapsUrl} target="_blank" rel="noopener noreferrer">Como chegar <span aria-hidden="true">↗</span></a><div className="church-contacts">{settings.whatsapp&&<a href={'https://wa.me/'+settings.whatsapp} target="_blank" rel="noopener noreferrer">Fale pelo WhatsApp</a>}{settings.instagram&&<a href={settings.instagram} target="_blank" rel="noopener noreferrer">Instagram da igreja</a>}</div><span className="welcome-word" aria-hidden="true">TENDA</span></section>
  </main>
  <footer><a className="footer-title" href="#inicio">TENDA DA ADORAÇÃO</a><p>Uma igreja reestruturando famílias.</p><a href="/administrador">Área de publicação ↗</a></footer>
</>;}
