'use client';
import {useEffect,useRef,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import type {Entry,Photo} from '@/lib/models';
import {dateLabel} from '@/lib/models';
const statuses={draft:'Rascunho',published:'Publicado',ended:'Encerrado',archived:'Arquivado'};
const fresh=(kind:'album'|'event'):Entry=>({id:'',kind,title:'',description:'',date:'',location:kind==='event'?'Rua Cartuana, 548 · Tiradentes, Porto Velho – RO':'',status:'draft',created_at:'',updated_at:'',photos:[]});
async function api<T=Record<string,string>>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,options);let body;try{body=await r.json();}catch{throw Error('Não foi possível conectar. Tente novamente.');}if(!r.ok)throw Error((body as {error?:string}).error||'Não foi possível salvar.');return body as T;}
async function optimize(file:File):Promise<File>{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Use imagens JPG, PNG ou WebP.');
 if(file.size>25*1024*1024)throw Error('Selecione uma foto menor que 25 MB.');
 const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,2000/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw Error('Este navegador não conseguiu preparar a foto.');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Não foi possível preparar a foto.')),'image/jpeg',.86));return new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'});}finally{bitmap.close();}
}
export default function Dashboard(){
 const [entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('album'),[editing,setEditing]=useState<Entry|null>(null),[busy,setBusy]=useState(false),[upload,setUpload]=useState<{done:number;total:number}|null>(null),[remove,setRemove]=useState<Photo|null>(null);
 const lock=useRef(false),formRef=useRef<HTMLFormElement>(null);
 async function refresh(){const rows:Entry[]=await api<Entry[]>('/api/entries?admin=1');setEntries(rows);return rows;}
 useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!editing)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editing]);
 function choose(entry:Entry){setEditing({...entry,photos:[...entry.photos]});setError('');requestAnimationFrame(()=>document.getElementById('editor')?.scrollIntoView({behavior:'smooth',block:'start'}));}
 async function save(status:Entry['status'],close=false){
  if(!editing||lock.current||!formRef.current?.reportValidity())return;
  lock.current=true;setBusy(true);setError('');
  try{let current={...editing,status};if(!current.id){const {id}=await api('/api/entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(current)});current={...current,id,status:'draft'};setEditing(current);}
   await api('/api/entries/'+current.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...current,status})});const rows=await refresh();setEditing(close?null:rows.find(e=>e.id===current.id)||current);toast.success(status==='published'?'Publicação disponível no site.':status==='ended'?'Evento encerrado.':status==='archived'?'Publicação retirada do site.':'Rascunho salvo.');
  }catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}
 }
 async function addPhotos(files:File[]){
  if(!editing||!files.length||lock.current)return;if(!formRef.current?.reportValidity())return;
  if(editing.photos.length+files.length>40){setError('Cada álbum ou evento permite até 40 fotos.');return;}
  lock.current=true;setBusy(true);setError('');setUpload({done:0,total:files.length});let current=editing;
  try{if(!current.id){const {id}=await api('/api/entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(current)});current={...current,id,status:'draft'};setEditing(current);}
   for(let i=0;i<files.length;i++){const file=await optimize(files[i]);const body=new FormData();body.set('file',file);await api('/api/entries/'+current.id+'/photos',{method:'POST',body});setUpload({done:i+1,total:files.length});}
   toast.success('Fotos enviadas. Confira o álbum antes de publicar.');
  }catch(e){setError((e as Error).message+' As fotos já enviadas foram mantidas.');}
  finally{try{const rows=await refresh();const saved=rows.find(e=>e.id===current.id);if(saved)setEditing({...current,photos:saved.photos});}catch{setError('Atualize a lista para conferir quais fotos foram enviadas.');}lock.current=false;setBusy(false);setUpload(null);}
 }
 async function deletePhoto(){if(!remove||busy)return;setBusy(true);try{await api('/api/photos/'+remove.id,{method:'DELETE'});setEditing(e=>e?{...e,photos:e.photos.filter(p=>p.id!==remove.id)}:e);await refresh();setRemove(null);toast.success('Foto removida.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function field<K extends keyof Entry>(key:K,value:Entry[K]){setEditing(e=>e?{...e,[key]:value}:e);}
 const localDate=editing?.date?new Date(new Date(editing.date).getTime()-4*60*60*1000).toISOString().slice(0,16):'';
 return <><Toaster/><Tabs value={tab} onValueChange={setTab}><div className="dashboard-toolbar"><TabsList><TabsTrigger value="album">Álbuns de fotos</TabsTrigger><TabsTrigger value="event">Eventos especiais</TabsTrigger></TabsList><Button onClick={()=>choose(fresh(tab as 'album'|'event'))} disabled={busy||!!editing}>+ {tab==='album'?'Novo álbum':'Novo evento'}</Button></div>{['album','event'].map(kind=><TabsContent value={kind} key={kind}>{loading?<p role="status">Carregando suas publicações…</p>:entries.filter(e=>e.kind===kind).length?<div className="admin-list">{entries.filter(e=>e.kind===kind).map(e=><article key={e.id} className="admin-entry">{e.photos[0]?<img src={'/api/media/'+e.photos[0].id} alt=""/>:<div className="entry-placeholder">{e.kind==='album'?'FOTOS':'EVENTO'}</div>}<div><span className={'badge status-'+e.status}>{statuses[e.status]}</span><h2>{e.title}</h2><p>{e.kind==='event'?dateLabel(e.date):e.photos.length+(e.photos.length===1?' foto':' fotos')}</p></div><Button variant="outline" disabled={busy||!!editing} onClick={()=>choose(e)}>Editar</Button></article>)}</div>:<Empty className="empty-block"><EmptyHeader><EmptyTitle>{kind==='album'?'Seu primeiro álbum começa aqui.':'Vamos organizar o próximo encontro?'}</EmptyTitle><EmptyDescription>{kind==='album'?'Crie um álbum e escolha as fotos na galeria do seu celular.':'Cadastre um evento com data, horário, local e uma imagem de divulgação.'}</EmptyDescription></EmptyHeader></Empty>}</TabsContent>)}</Tabs>
 {error&&<div role="alert" className="notice error">{error} {!editing&&<button onClick={()=>{setError('');refresh().catch(e=>setError(e.message));}}>Tentar novamente</button>}</div>}
 {editing&&<section id="editor" className="editor"><div className="editor-heading"><div><span className="eyebrow">{editing.kind==='album'?'ÁLBUM DE FOTOS':'EVENTO ESPECIAL'}</span><h2>{editing.id?'Editar publicação':'Nova publicação'}</h2></div><Button variant="ghost" disabled={busy} onClick={()=>setEditing(null)}>Fechar edição</Button></div><form ref={formRef} onSubmit={e=>{e.preventDefault();void save(editing.status);}}><fieldset disabled={busy}><label htmlFor="title">Título</label><Input id="title" required maxLength={120} value={editing.title} onChange={e=>field('title',e.target.value)} placeholder={editing.kind==='album'?'Ex.: Culto da Família':'Ex.: Encontro de Famílias'}/><label htmlFor="description">Descrição</label><Textarea id="description" maxLength={3000} rows={4} value={editing.description} onChange={e=>field('description',e.target.value)} placeholder="Conte um pouco sobre este momento…"/>{editing.kind==='event'&&<div className="form-grid"><div><label htmlFor="date">Data e horário · Porto Velho</label><Input id="date" type="datetime-local" required value={localDate} onChange={e=>field('date',e.target.value?e.target.value+':00-04:00':'')}/></div><div><label htmlFor="location">Local</label><Input id="location" required maxLength={240} value={editing.location} onChange={e=>field('location',e.target.value)}/></div></div>}<div className="upload-area"><label htmlFor="photos">{editing.kind==='album'?'Adicionar fotos':'Adicionar imagem de divulgação'}</label><p>JPG, PNG ou WebP. Até 40 fotos. As imagens são ajustadas para carregar bem no celular.</p><Input id="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{void addPhotos(Array.from(e.target.files??[]));e.target.value='';}}/></div>{upload&&<div role="status"><p>Enviando {upload.done} de {upload.total} fotos…</p><Progress value={upload.done/upload.total*100}/></div>}<div className="photo-preview">{editing.photos.map((p,i)=><div key={p.id}><img src={'/api/media/'+p.id} alt={p.caption||'Foto '+(i+1)}/><Button type="button" variant="outline" size="sm" onClick={()=>setRemove(p)} aria-label={'Remover foto '+(i+1)}>Remover</Button>{i===0&&<span>Capa</span>}</div>)}</div><div className="editor-actions"><Button type="button" onClick={()=>save('published',true)} disabled={editing.kind==='album'&&!editing.photos.length}>{busy?'Salvando…':editing.status==='published'?'Salvar e publicar':'Publicar no site'}</Button><Button type="button" variant="outline" onClick={()=>save('draft')}>Salvar rascunho</Button>{editing.id&&editing.kind==='event'&&<Button type="button" variant="outline" onClick={()=>save('ended',true)}>Encerrar evento</Button>}{editing.id&&<Button type="button" variant="ghost" onClick={()=>save('archived',true)}>Arquivar</Button>}</div><p className="editor-hint">Rascunhos e publicações arquivadas ficam visíveis apenas neste painel.</p></fieldset></form></section>}
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remover esta foto?</AlertDialogTitle><AlertDialogDescription>A foto será retirada do álbum e do site. Para recuperá-la, será necessário enviá-la novamente.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void deletePhoto();}}>Remover foto</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

